version: '3.7'
services:
  http:
    image: muninn/restdemo
    ports:
      - 1328:1324
    environment:
      - CONFIGOR_ENV_PREFIX=-
      - APP_DEBUG=false
      - APP_BASEURL=https://demo.crandom.com/
      - APP_FILEURL=https://static.crandom.com/
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=demo
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
